name: Generate Jekyll Archives
# description: Generate categories, tags and years archive files.
on:
  workflow_dispatch:
  push:
    paths:
      - "_posts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/kannansuresh/jekyll-blog-archive-workflow/issues/7
      # Remove when this is fixed
      - name: Make sure the archive directories exist
        run: |
          mkdir -p _archives/categories
          mkdir -p _archives/tags
          mkdir -p _archives/years

      - name: Jekyll Blog Archive
        uses: kannansuresh/jekyll-blog-archive-workflow@v1.0.3
        with:
          archive_url: "https://gh-blog.penguineering.com/archives/archivedata"
          archive_folder_path: "_archives"

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add --all
          git commit -m "Created and updated archive files." || echo "No changes to commit."
          git push origin master || echo "No changes to push."
